### ISSUE TITLE
Is it possible to remove the payor account from last months billing group?

### ISSUE THREAD

**Issue by ptyo** [aws-samples/aws-billing-conductor-sp-ri-benefit-utility#4]
The payer (or account where purchases are centrally made) must not belong to a billing group. It also assumes that there is at least one month of ABC data for each billing group given that it looks back to the previous month.

I deleted the existing billing group that contains the Main Payor, but that on fixes it for this month. Is it possible to delete from last month as you recommend it shouldn't be in a billing group.

**Comment by scottenriquez** [comment]
@ptyo, you can do so via a backfill. From the [FAQs](https://aws.amazon.com/aws-cost-management/aws-billing-conductor/faqs/):

> You can request a backfill of your existing billing group configuration. To do so, please cut a ticket to support and specify the billing group name and time period you need. Limitations apply.

Please let me know if this helps!

**Comment by ptyo** [comment]
alright thanks I will do that. I am trying to use the code you all created to do other custom line items to fit our needs..

**Comment by ptyo** [comment]
I did as you suggested and just waiting for the service team to backfill per my request.

**Comment by ptyo** [comment]
The service team got back to me and said the following: 

"This is the expected behavior across resources created through Billing Conductor. Billing groups, pricing plans, and pricing rules can only be created/modified/deleted within the current billing period. This is because the historical configurations are considered immutable once the month rolls over and the previous billing period is considered "closed". (The only exception to this is custom line items, which can be configured for the previous billing period.)
